# config/services.yaml
# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    # Paramètres personnalisés
    app.base_url: '%env(APP_BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances
        autoconfigure: true # Enregistre automatiquement les services (commandes, event subscribers, etc.)
        public: false       # Tous les services sont privés par défaut (sauf explicitement publics)

    # Makes classes in src/ available as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Exemple d'override ou service explicite si besoin
    # App\Service\MyService:
    #     arguments:
    #         $someParameter: '%app.base_url%'
